const HTTP_OK = 200;
const HTTP_CREATED = 201;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_UNPROCESSSABLE_ENTITY = 422;
const HTTP_NO_CONTENT = 204;
const HTTP_INTERNAL_SERVER_ERROR = 500;
const HTTP_NOT_FOUND = 404;

module.exports = {
	HTTP_BAD_REQUEST,
	HTTP_CREATED,
	HTTP_OK,
	HTTP_UNAUTHORIZED,
  HTTP_UNPROCESSSABLE_ENTITY,
	HTTP_NO_CONTENT,
	HTTP_INTERNAL_SERVER_ERROR,
  HTTP_NOT_FOUND
};